filter:
    paths: [ src/* ]
    excluded_paths:
        - vendor/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true