language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
    - mkdir -p build/logs
#    - ./vendor/phpunit/phpunit/phpunit -c app/
    - whereis node
    - which node
    - cd node/ && npm install && cd ../
    - make tests

after_script:
    - php bin/coveralls