language: php

php:
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
    # This line avoid weird error about permission when it try to clear:cache
#    - rm -rf app/cache
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
    - ./vendor/phpunit/phpunit/phpunit -c app/