language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
    - mkdir -p build/logs
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
#    - ./vendor/phpunit/phpunit/phpunit -c app/
    # /home/travis/.nvm/v0.10.36/bin/node
    - which node
    - cd node/ && npm install && cd ../
    - make tests

after_script:
    - php bin/coveralls