imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    channels: [bitdepot_notices]
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false

doctrine_cache:
    aliases:
        cache_nonces: apc_cache

    providers:
        apc_cache:
            type: apcu # set apcu only on config_dev.yml, because the remote server is on PHP5, and my local (dev) env is on PHP7
            namespace: apc_cache

#swiftmailer:
#    delivery_address: me@example.com
