security:
    role_hierarchy:
        # When a user is logged via AngularJS
        ROLE_USER:
            - DEPOSIT_LIST
            - DEPOSIT_CREATE
            - WITHDRAW_LIST

        # When an application is logged via WSSE
        ROLE_WSSE:
            - DEPOSIT_CREATE

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        # Only for JWT-Auth
        fos_userbundle:
            id: fos_user.user_provider.username

#        in_memory:
#            memory:
#                users:
#                    application_1: { password: 'testpass', roles: 'ROLE_WSSE' }

        # Only for WSSE-Auth
        wsse_application:
            id: dizda_app.security.application_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/
            stateless: true

            # JWT-Auth, for users only
            lexik_jwt: ~

            # WSSE-Auth, for application only
            wsse:
                provider: wsse_application
                realm: "Secured with WSSE" #identifies the set of resources to which the authentication information will apply (WWW-Authenticate)
                profile: "UsernameToken" #WSSE profile (WWW-Authenticate)

    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }